[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | venv
)/
'''

[tool.pycln]
all = true

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

[tool.mypy]
python_version = 3.11
plugins = "sqlalchemy.ext.mypy.plugin"

[[tool.mypy.overrides]]
module = "precisely.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = 'fixtures.*'
ignore_missing_imports = true
