"""Add new DB index to ticker and date together

Revision ID: bffa595c60b9
Revises: 31aa7d3383c0
Create Date: 2023-12-23 18:30:04.124786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffa595c60b9'
down_revision: Union[str, None] = '31aa7d3383c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ticker_data_negocio', 'stock_quotes', ['ticker', 'data_negocio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ticker_data_negocio', table_name='stock_quotes')
    # ### end Alembic commands ###
